
services:
  mongodb:
    container_name: fix-me-mongo
    image: mongo
    restart: no
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_PASSWORD}
    ports:
      - 27017:27017 # default mongodb port
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: fix-me-mongo
    driver: local

